name: drupal-testing-workshop
recipe: drupal9
config:
  webroot: web
  composer_version: 2
services:
  appserver:
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install --global yarn
    build:
      - composer install
      - mkdir -p private/browsertest_output
      - yarn install --non-interactive --cwd /app/web/core
    overrides:
      environment:
        # PHPUnit
        SYMFONY_DEPRECATIONS_HELPER: weak
        SIMPLETEST_DB: 'mysql://drupal9:drupal9@database:3306/drupal9'
        SIMPLETEST_BASE_URL: 'http://appserver'
        BROWSERTEST_OUTPUT_DIRECTORY: /app/private/browsertest_output
        # @todo is there a way to dynamically set this in .lando.yml?
        # like have this read from $LANDO_DOMAIN
        BROWSERTEST_OUTPUT_BASE_URL: https://nightwatch-training.lndo.site/
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chromedriver:9515"]'

        # Nightwatch
        DRUPAL_TEST_BASE_URL: 'http://appserver'
        DRUPAL_TEST_DB_URL: 'mysql://drupal9:drupal9@database:3306/drupal9'
        DRUPAL_TEST_WEBDRIVER_HOSTNAME: chromedriver
        DRUPAL_TEST_WEBDRIVER_PORT: 9515
        DRUPAL_TEST_CHROMEDRIVER_AUTOSTART: 'false'
        DRUPAL_TEST_WEBDRIVER_CHROME_ARGS: "--disable-gpu --headless --no-sandbox"
        DRUPAL_NIGHTWATCH_OUTPUT: reports/nightwatch
        DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
  chromedriver:
    type: compose
    services:
      image: drupalci/chromedriver:production
      # Lando always overrides the default entrypoint.
      command: chromedriver --verbose --whitelisted-ips=
tooling:
  phpunit:
    service: appserver
    description: Run phpunit
    cmd: php /app/vendor/bin/phpunit -c core/phpunit.xml.dist
    dir: /app/web
  nightwatch:
    service: appserver
    description: Run Nightwatch.js
    cmd: yarn test:nightwatch
    dir: /app/web/core
