name: DDEV
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jonaseberle/github-action-setup-ddev@v1
      - run: ddev phpunit core/modules/action --debug
      - run: ddev nightwatch --tag quicklink --tag workshop
      - run: ddev logs -s chromedriver
        if: ${{ failure() }}
